/*
 * Swagger diff server
 *
 * This is a sample diff server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ResponseBody : IEquatable<ResponseBody>
    { 
        /// <summary>
        /// Gets or Sets DiffResultType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DiffResultTypeEnum
        {
            
            /// <summary>
            /// Enum EqualsEnum for Equals
            /// </summary>
            [EnumMember(Value = "Equals")]
            EqualsEnum = 1,
            
            /// <summary>
            /// Enum ContentDoNotMatchEnum for ContentDoNotMatch
            /// </summary>
            [EnumMember(Value = "ContentDoNotMatch")]
            ContentDoNotMatchEnum = 2,
            
            /// <summary>
            /// Enum SizeDoNotMatchEnum for SizeDoNotMatch
            /// </summary>
            [EnumMember(Value = "SizeDoNotMatch")]
            SizeDoNotMatchEnum = 3
        }

        /// <summary>
        /// Gets or Sets DiffResultType
        /// </summary>

        [DataMember(Name="diffResultType")]
        public DiffResultTypeEnum? DiffResultType { get; set; }

        /// <summary>
        /// Gets or Sets Diffs
        /// </summary>

        [DataMember(Name="diffs")]
        public DiffObject Diffs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseBody {\n");
            sb.Append("  DiffResultType: ").Append(DiffResultType).Append("\n");
            sb.Append("  Diffs: ").Append(Diffs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ResponseBody)obj);
        }

        /// <summary>
        /// Returns true if ResponseBody instances are equal
        /// </summary>
        /// <param name="other">Instance of ResponseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseBody other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DiffResultType == other.DiffResultType ||
                    DiffResultType != null &&
                    DiffResultType.Equals(other.DiffResultType)
                ) && 
                (
                    Diffs == other.Diffs ||
                    Diffs != null &&
                    Diffs.Equals(other.Diffs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DiffResultType != null)
                    hashCode = hashCode * 59 + DiffResultType.GetHashCode();
                    if (Diffs != null)
                    hashCode = hashCode * 59 + Diffs.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ResponseBody left, ResponseBody right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ResponseBody left, ResponseBody right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
