/* 
 * Swagger diff server
 *
 * This is a sample diff server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseBodyTests
    {
        // TODO uncomment below to declare an instance variable for ResponseBody
        //private ResponseBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseBody
            //instance = new ResponseBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseBody
        /// </summary>
        [Test]
        public void ResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseBody
            //Assert.IsInstanceOfType<ResponseBody> (instance, "variable 'instance' is a ResponseBody");
        }


        /// <summary>
        /// Test the property 'DiffResultType'
        /// </summary>
        [Test]
        public void DiffResultTypeTest()
        {
            // TODO unit test for the property 'DiffResultType'
        }
        /// <summary>
        /// Test the property 'Diffs'
        /// </summary>
        [Test]
        public void DiffsTest()
        {
            // TODO unit test for the property 'Diffs'
        }

    }

}
